# This file was automatically generated by dhmk.pl
# DO NOT edit as your changes will eventually be lost.
# DO NOT include this file in the source package.

# Action command sequences
clean_dh_testdir = dh_testdir
clean_dh_auto_clean = dh_auto_clean '--buildsystem=kf5'
clean_dh_clean = dh_clean
dhmk_clean_commands = dh_testdir dh_auto_clean dh_clean
dhmk_clean_depends = 

install-arch_dh_testroot = dh_testroot
install-arch_dh_prep = dh_prep
install-arch_dh_installdirs = dh_installdirs
install-arch_dh_auto_install = dh_auto_install '--buildsystem=kf5'
install-arch_dh_install = dh_install
install-arch_dh_movelibkdeinit = dh_movelibkdeinit
install-arch_dh_installdocs = dh_installdocs
install-arch_dh_installchangelogs = dh_installchangelogs
install-arch_dh_installexamples = dh_installexamples
install-arch_dh_installman = dh_installman
install-arch_dh_installcatalogs = dh_installcatalogs
install-arch_dh_installcron = dh_installcron
install-arch_dh_installdebconf = dh_installdebconf
install-arch_dh_installemacsen = dh_installemacsen
install-arch_dh_installifupdown = dh_installifupdown
install-arch_dh_installinfo = dh_installinfo
install-arch_dh_installinit = dh_installinit
install-arch_dh_installmenu = dh_installmenu
install-arch_dh_installmime = dh_installmime
install-arch_dh_installmodules = dh_installmodules
install-arch_dh_installlogcheck = dh_installlogcheck
install-arch_dh_installlogrotate = dh_installlogrotate
install-arch_dh_installpam = dh_installpam
install-arch_dh_installppp = dh_installppp
install-arch_dh_installudev = dh_installudev
install-arch_dh_installwm = dh_installwm
install-arch_dh_installxfonts = dh_installxfonts
install-arch_dh_bugfiles = dh_bugfiles
install-arch_dh_lintian = dh_lintian
install-arch_dh_gconf = dh_gconf
install-arch_dh_icons = dh_icons
install-arch_dh_perl = dh_perl
install-arch_dh_usrlocal = dh_usrlocal
install-arch_dh_link = dh_link
install-arch_dh_compress = dh_compress '-X.dcl' '-X.docbook' '-X-license' '-X.tag' '-X.sty' '-X.el'
install-arch_dh_fixperms = dh_fixperms
dhmk_install-arch_commands = dh_testroot dh_prep dh_installdirs dh_auto_install dh_install dh_movelibkdeinit dh_installdocs dh_installchangelogs dh_installexamples dh_installman dh_installcatalogs dh_installcron dh_installdebconf dh_installemacsen dh_installifupdown dh_installinfo dh_installinit dh_installmenu dh_installmime dh_installmodules dh_installlogcheck dh_installlogrotate dh_installpam dh_installppp dh_installudev dh_installwm dh_installxfonts dh_bugfiles dh_lintian dh_gconf dh_icons dh_perl dh_usrlocal dh_link dh_compress dh_fixperms
dhmk_install-arch_depends = build-arch

configure_dh_testdir = dh_testdir
configure_dh_auto_configure = dh_auto_configure '--buildsystem=kf5'
dhmk_configure_commands = dh_testdir dh_auto_configure
dhmk_configure_depends = 

binary-arch_dh_strip = dh_strip
binary-arch_dh_makeshlibs = dh_makeshlibs '-Xusr/lib/libkdeinit5_*'
binary-arch_dh_shlibdeps = dh_shlibdeps
binary-arch_dh_installdeb = dh_installdeb
binary-arch_dh_gencontrol = dh_gencontrol
binary-arch_dh_md5sums = dh_md5sums
binary-arch_dh_builddeb = dh_builddeb
dhmk_binary-arch_commands = dh_strip dh_makeshlibs dh_shlibdeps dh_installdeb dh_gencontrol dh_md5sums dh_builddeb
dhmk_binary-arch_depends = install-arch

binary-indep_dh_installdeb = dh_installdeb
binary-indep_dh_gencontrol = dh_gencontrol
binary-indep_dh_md5sums = dh_md5sums
binary-indep_dh_builddeb = dh_builddeb
dhmk_binary-indep_commands = dh_installdeb dh_gencontrol dh_md5sums dh_builddeb
dhmk_binary-indep_depends = install-indep

binary_dh_strip = dh_strip
binary_dh_makeshlibs = dh_makeshlibs '-Xusr/lib/libkdeinit5_*'
binary_dh_shlibdeps = dh_shlibdeps
binary_dh_installdeb = dh_installdeb
binary_dh_gencontrol = dh_gencontrol
binary_dh_md5sums = dh_md5sums
binary_dh_builddeb = dh_builddeb
dhmk_binary_commands = dh_strip dh_makeshlibs dh_shlibdeps dh_installdeb dh_gencontrol dh_md5sums dh_builddeb
dhmk_binary_depends = install

build_dh_testdir = dh_testdir
build_dh_auto_build = dh_auto_build '--buildsystem=kf5'
build_dh_auto_test = dh_auto_test '--buildsystem=kf5'
dhmk_build_commands = dh_testdir dh_auto_build dh_auto_test
dhmk_build_depends = configure

build-arch_dh_testdir = dh_testdir
build-arch_dh_auto_build = dh_auto_build '--buildsystem=kf5'
build-arch_dh_auto_test = dh_auto_test '--buildsystem=kf5'
dhmk_build-arch_commands = dh_testdir dh_auto_build dh_auto_test
dhmk_build-arch_depends = configure

build-indep_dh_testdir = dh_testdir
build-indep_dh_auto_build = dh_auto_build '--buildsystem=kf5'
build-indep_dh_auto_test = dh_auto_test '--buildsystem=kf5'
dhmk_build-indep_commands = dh_testdir dh_auto_build dh_auto_test
dhmk_build-indep_depends = configure

install-indep_dh_testroot = dh_testroot
install-indep_dh_prep = dh_prep
install-indep_dh_installdirs = dh_installdirs
install-indep_dh_auto_install = dh_auto_install '--buildsystem=kf5'
install-indep_dh_install = dh_install
install-indep_dh_movelibkdeinit = dh_movelibkdeinit
install-indep_dh_installdocs = dh_installdocs
install-indep_dh_installchangelogs = dh_installchangelogs
install-indep_dh_installexamples = dh_installexamples
install-indep_dh_installman = dh_installman
install-indep_dh_installcatalogs = dh_installcatalogs
install-indep_dh_installcron = dh_installcron
install-indep_dh_installdebconf = dh_installdebconf
install-indep_dh_installemacsen = dh_installemacsen
install-indep_dh_installifupdown = dh_installifupdown
install-indep_dh_installinfo = dh_installinfo
install-indep_dh_installinit = dh_installinit
install-indep_dh_installmenu = dh_installmenu
install-indep_dh_installmime = dh_installmime
install-indep_dh_installmodules = dh_installmodules
install-indep_dh_installlogcheck = dh_installlogcheck
install-indep_dh_installlogrotate = dh_installlogrotate
install-indep_dh_installpam = dh_installpam
install-indep_dh_installppp = dh_installppp
install-indep_dh_installudev = dh_installudev
install-indep_dh_installwm = dh_installwm
install-indep_dh_installxfonts = dh_installxfonts
install-indep_dh_bugfiles = dh_bugfiles
install-indep_dh_lintian = dh_lintian
install-indep_dh_gconf = dh_gconf
install-indep_dh_icons = dh_icons
install-indep_dh_perl = dh_perl
install-indep_dh_usrlocal = dh_usrlocal
install-indep_dh_link = dh_link
install-indep_dh_compress = dh_compress '-X.dcl' '-X.docbook' '-X-license' '-X.tag' '-X.sty' '-X.el'
install-indep_dh_fixperms = dh_fixperms
dhmk_install-indep_commands = dh_testroot dh_prep dh_installdirs dh_auto_install dh_install dh_movelibkdeinit dh_installdocs dh_installchangelogs dh_installexamples dh_installman dh_installcatalogs dh_installcron dh_installdebconf dh_installemacsen dh_installifupdown dh_installinfo dh_installinit dh_installmenu dh_installmime dh_installmodules dh_installlogcheck dh_installlogrotate dh_installpam dh_installppp dh_installudev dh_installwm dh_installxfonts dh_bugfiles dh_lintian dh_gconf dh_icons dh_perl dh_usrlocal dh_link dh_compress dh_fixperms
dhmk_install-indep_depends = build-indep

install_dh_testroot = dh_testroot
install_dh_prep = dh_prep
install_dh_installdirs = dh_installdirs
install_dh_auto_install = dh_auto_install '--buildsystem=kf5'
install_dh_install = dh_install
install_dh_movelibkdeinit = dh_movelibkdeinit
install_dh_installdocs = dh_installdocs
install_dh_installchangelogs = dh_installchangelogs
install_dh_installexamples = dh_installexamples
install_dh_installman = dh_installman
install_dh_installcatalogs = dh_installcatalogs
install_dh_installcron = dh_installcron
install_dh_installdebconf = dh_installdebconf
install_dh_installemacsen = dh_installemacsen
install_dh_installifupdown = dh_installifupdown
install_dh_installinfo = dh_installinfo
install_dh_installinit = dh_installinit
install_dh_installmenu = dh_installmenu
install_dh_installmime = dh_installmime
install_dh_installmodules = dh_installmodules
install_dh_installlogcheck = dh_installlogcheck
install_dh_installlogrotate = dh_installlogrotate
install_dh_installpam = dh_installpam
install_dh_installppp = dh_installppp
install_dh_installudev = dh_installudev
install_dh_installwm = dh_installwm
install_dh_installxfonts = dh_installxfonts
install_dh_bugfiles = dh_bugfiles
install_dh_lintian = dh_lintian
install_dh_gconf = dh_gconf
install_dh_icons = dh_icons
install_dh_perl = dh_perl
install_dh_usrlocal = dh_usrlocal
install_dh_link = dh_link
install_dh_compress = dh_compress '-X.dcl' '-X.docbook' '-X-license' '-X.tag' '-X.sty' '-X.el'
install_dh_fixperms = dh_fixperms
dhmk_install_commands = dh_testroot dh_prep dh_installdirs dh_auto_install dh_install dh_movelibkdeinit dh_installdocs dh_installchangelogs dh_installexamples dh_installman dh_installcatalogs dh_installcron dh_installdebconf dh_installemacsen dh_installifupdown dh_installinfo dh_installinit dh_installmenu dh_installmime dh_installmodules dh_installlogcheck dh_installlogrotate dh_installpam dh_installppp dh_installudev dh_installwm dh_installxfonts dh_bugfiles dh_lintian dh_gconf dh_icons dh_perl dh_usrlocal dh_link dh_compress dh_fixperms
dhmk_install_depends = build

# Overrides
dhmk_override_dh_auto_test = yes
dhmk_override_dh_strip = yes

# Export environment changes
dhmk_envvar_orig_PATH := $(PATH)
define PATH
/usr/share/pkg-kde-tools/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11
endef
debian/dhmk_rules.mk: PATH = $(dhmk_envvar_orig_PATH)

